### ISSUE TITLE
Wrong Document Root on screenshot

### ISSUE THREAD

**Issue by sebj54** [pi0/nuxt-plesk-demo#3]
Hi there!

Thanks for your clear tutorial, it saved me a lot of time!

I just found an error in the screenshot below:

![](https://user-images.githubusercontent.com/5158436/47367570-cc1eda00-d6ec-11e8-84e5-a1bcab4c3812.png)

Document Root should be `httpdocs`, maybe in the other screenshot too!

**Comment by seybsen** [comment]
Setting the Document Root to `/httpdocs` would allow everyone to browse your source files like for example http://nuxt.127.0.0.1.xip.io/nuxt.config.js which could be a security issue.

**Comment by sebj54** [comment]
You're right, this is a non issue so!
I don't know why, but it didn't work when I tested this configuration. No it's working as expected.

Thanks for the heads up!
